### PR TITLE
Fix microseconds formatting

### LINKED ISSUE #5: %f format behaves incorrectly
Different to other formats, the padding on %f should be a trailing pad. For example, this:

    NimbleStrftime.format(~U"2019-08-15 17:07:57.001Z", "%I:%M:%S.%f %p")

is formatted as:

    "05:07:57.1000 PM"

which is not correct. I believe by default it should be formatted using the padding in the datetime struct (which is the second element of the microsecond field).

So `~U"2019-08-15 17:07:57.001Z"` should be padded as `57.001` but `~U"2019-08-15 17:07:57.001000Z"` should be padded as `57.001000`. The user can force a particular padding but I think in this case it will be more like a precision rather than padding. So if I say the "padding" is 1, we will only ever show the first digit.

How do other `strftime` implementations behave here?

### PR DESCRIPTION
**Pull request by GustavoSantosFe**
closes #5 
the microseconds format was behaving incorrectly and giving a wrong number
this PR fixes this and removes the padding and width options from the microsecond format as discussed [on the issue #5](/plataformatec/nimble_strftime/issues/5)

### CODE REVIEW

File: lib/nimble_strftime.ex [hunk 1]
```diff
@@ -34,7 +34,7 @@ defmodule NimbleStrftime do
   B      | Full month name                                                         | January
   c      | Preferred date+time representation                                      | 2018-10-17 12:34:56
   d      | Day of the month                                                        | 01, 12
-  f      | Microseconds                                                            | 000000, 999999, 0123
+  f      | Microseconds**(this format ignores width and padding options)**             | 000000, 999999, 0123
```
Comment (josevalim) [inline lib/nimble_strftime.ex]: Bold is probably too much as it could attention to this particular line. Maybe:

```suggestion
  f      | Microseconds *(does not support width and padding options)*             | 000000, 999999, 0123
```

File: lib/nimble_strftime.ex [hunk 2]
```diff
@@ -312,8 +312,9 @@ defmodule NimbleStrftime do
   end
 
   # Microseconds
-  defp format_modifiers("f" <> rest, width, pad, datetime, format_options, acc) do
-    result = datetime.microsecond |> elem(0) |> Integer.to_string() |> pad_leading(width, pad)
+  defp format_modifiers("f" <> rest, _width, _pad, datetime, format_options, acc) do
+    {microsecond, precision} = datetime.microsecond
+    result = microsecond |> Integer.to_string() |> pad_leading(6, "0") |> IO.iodata_to_binary() |> binary_part(0, precision)
```
Comment (josevalim) [inline lib/nimble_strftime.ex]:
```suggestion
    result = microsecond |> Integer.to_string() |> String.pad_leading(6, "0") |> binary_part(0, precision)
```

File: test/nimble_strftime_test.exs [hunk 3]
```diff
@@ -131,12 +131,20 @@ defmodule NimbleStrftimeTest do
       assert NimbleStrftime.format(%{month: 12}, "%B %b") == "December Dec"
     end
 
+    test "microseconds format ignores padding and width options" do
+      datetime = ~U[2019-08-15 17:07:57.001234Z]
+      assert NimbleStrftime.format(datetime, "%f") == "001234"
+      assert NimbleStrftime.format(datetime, "%f") == NimbleStrftime.format(datetime, "%_20f")
+      assert NimbleStrftime.format(datetime, "%f") == NimbleStrftime.format(datetime, "%020f")
+      assert NimbleStrftime.format(datetime, "%f") == NimbleStrftime.format(datetime, "%-f")
```
Comment (josevalim) [inline test/nimble_strftime_test.exs]: We need more tests. Especially tests that include:

1. Naive datetimes with different precisions (.1, .123, .123456)
2. Naive datetimes with 0 micrsoeconds in different precisions (.0, .00, .000000)
3. Naive datetimes with no precision (which we may have to round to `"0"`

File: lib/nimble_strftime.ex [hunk 4]
```diff
@@ -312,8 +312,9 @@ defmodule NimbleStrftime do
   end
 
   # Microseconds
-  defp format_modifiers("f" <> rest, width, pad, datetime, format_options, acc) do
-    result = datetime.microsecond |> elem(0) |> Integer.to_string() |> pad_leading(width, pad)
+  defp format_modifiers("f" <> rest, _width, _pad, datetime, format_options, acc) do
+    {microsecond, precision} = datetime.microsecond
+    result = microsecond |> Integer.to_string() |> String.pad_leading(6, "0") |> binary_part(0, max(precision,1))
```
Comment (josevalim) [inline lib/nimble_strftime.ex]:
```suggestion
    result = microsecond |> Integer.to_string() |> String.pad_leading(6, "0") |> binary_part(0, max(precision, 1))
```

Otherwise the formatter will fail later. :) Speaking about it... we should probably setup CI!
